# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acovtomaC <- function(g, code, tol, max_iter) {
    .Call(`_tfarima_acovtomaC`, g, code, tol, max_iter)
}

decompHC <- function(T, mu) {
    .Call(`_tfarima_decompHC`, T, mu)
}

decompFC <- function(T, mu) {
    .Call(`_tfarima_decompFC`, T, mu)
}

deceffBC <- function(y, bc, mu, phi, nabla, theta, sig2, F, type) {
    .Call(`_tfarima_deceffBC`, y, bc, mu, phi, nabla, theta, sig2, F, type)
}

seasadjC <- function(y, bc, mu, phi, nabla, theta, sig2, ariroots, method) {
    .Call(`_tfarima_seasadjC`, y, bc, mu, phi, nabla, theta, sig2, ariroots, method)
}

diffC <- function(z, nabla, bc) {
    .Call(`_tfarima_diffC`, z, nabla, bc)
}

filterC <- function(x, omega, delta, b) {
    .Call(`_tfarima_filterC`, x, omega, delta, b)
}

forecastC <- function(y, bc, mu, phi, nabla, theta, sig2, ori, hor) {
    .Call(`_tfarima_forecastC`, y, bc, mu, phi, nabla, theta, sig2, ori, hor)
}

backcastC <- function(y, bc, mu, phi, nabla, theta, sig2, ori, hor) {
    .Call(`_tfarima_backcastC`, y, bc, mu, phi, nabla, theta, sig2, ori, hor)
}

glsC <- function(y, X, phi, theta) {
    .Call(`_tfarima_glsC`, y, X, phi, theta)
}

ellarmaC <- function(w, phi, theta) {
    .Call(`_tfarima_ellarmaC`, w, phi, theta)
}

gresC <- function(w, phi, theta) {
    .Call(`_tfarima_gresC`, w, phi, theta)
}

ssrC <- function(w, phi, theta) {
    .Call(`_tfarima_ssrC`, w, phi, theta)
}

cllarmaC <- function(w, phi, theta) {
    .Call(`_tfarima_cllarmaC`, w, phi, theta)
}

outliersC <- function(z, bc, mu, phi, nabla, theta, types, timing, eres, c) {
    .Call(`_tfarima_outliersC`, z, bc, mu, phi, nabla, theta, types, timing, eres, c)
}

polyevalC <- function(pol, z) {
    .Call(`_tfarima_polyevalC`, pol, z)
}

polyrootsC <- function(pol) {
    .Call(`_tfarima_polyrootsC`, pol)
}

sortrootsC <- function(r) {
    .Call(`_tfarima_sortrootsC`, r)
}

combinerootsC <- function(T) {
    .Call(`_tfarima_combinerootsC`, T)
}

roots2polC <- function(A, check) {
    .Call(`_tfarima_roots2polC`, A, check)
}

admregC <- function(pol, ar) {
    .Call(`_tfarima_admregC`, pol, ar)
}

polymultC <- function(pol1, pol2) {
    .Call(`_tfarima_polymultC`, pol1, pol2)
}

polydivC <- function(pol1, pol2, rem, tol) {
    .Call(`_tfarima_polydivC`, pol1, pol2, rem, tol)
}

polygcdC <- function(pol1, pol2, tol) {
    .Call(`_tfarima_polygcdC`, pol1, pol2, tol)
}

polyprsC <- function(pol1, pol2) {
    .Call(`_tfarima_polyprsC`, pol1, pol2)
}

polyraiseC <- function(pol, d) {
    .Call(`_tfarima_polyraiseC`, pol, d)
}

polyratioC <- function(num, den, d) {
    .Call(`_tfarima_polyratioC`, num, den, d)
}

presampleCovC <- function(phi, theta, fvf) {
    .Call(`_tfarima_presampleCovC`, phi, theta, fvf)
}

condresC <- function(w, phi, theta, forward) {
    .Call(`_tfarima_condresC`, w, phi, theta, forward)
}

condres0C <- function(w, phi, theta, w0, a0, forward) {
    .Call(`_tfarima_condres0C`, w, phi, theta, w0, a0, forward)
}

inicondC <- function(w, phi, theta) {
    .Call(`_tfarima_inicondC`, w, phi, theta)
}

exactresC <- function(w, phi, theta) {
    .Call(`_tfarima_exactresC`, w, phi, theta)
}

cssrC <- function(w, phi, theta) {
    .Call(`_tfarima_cssrC`, w, phi, theta)
}

simC <- function(a, a0, bc, mu, phi, nabla, theta, y0) {
    .Call(`_tfarima_simC`, a, a0, bc, mu, phi, nabla, theta, y0)
}

spectrumC <- function(phi, theta, sigma2, nfreq) {
    .Call(`_tfarima_spectrumC`, phi, theta, sigma2, nfreq)
}

pgramC <- function(y, cpgram) {
    .Call(`_tfarima_pgramC`, y, cpgram)
}

bandchol <- function(A, L, detL) {
    .Call(`_tfarima_bandchol`, A, L, detL)
}

llrfC <- function(w, nabla, b, C, S, s2, cform) {
    .Call(`_tfarima_llrfC`, w, nabla, b, C, S, s2, cform)
}

llucaC <- function(w, phi, A, S, s2, res) {
    .Call(`_tfarima_llucaC`, w, phi, A, S, s2, res)
}

resrfC <- function(w, nabla, b, C, S, s2, cform) {
    .Call(`_tfarima_resrfC`, w, nabla, b, C, S, s2, cform)
}

kf0C <- function(y, b, C, S, x0, P0, v, s2) {
    .Call(`_tfarima_kf0C`, y, b, C, S, x0, P0, v, s2)
}

kfC <- function(y, b, C, S, x0, P0, v, s2, X, PX, filtered) {
    .Call(`_tfarima_kfC`, y, b, C, S, x0, P0, v, s2, X, PX, filtered)
}

ksC <- function(y, b, C, S, x0, P0, X, PX) {
    .Call(`_tfarima_ksC`, y, b, C, S, x0, P0, X, PX)
}

tacovC <- function(phi, theta, sigma2, nlags) {
    .Call(`_tfarima_tacovC`, phi, theta, sigma2, nlags)
}

pacorrC <- function(phi, theta, nlags) {
    .Call(`_tfarima_pacorrC`, phi, theta, nlags)
}

